# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1945f648a0cb4fef8c97a97e243830f2b8b63fcf9e9affca0fd7d3927b636b40d350c11701a08f8194c87a851d594f88f94b5ae3b3be5c435bfb82991cf76a8a

test:
  secret_key_base: 31cb99d16b7f359ce75ff39dd340b1b0f5d27a80fde8b21543f275a85db14d55aa70d3f1097ba80a625f366aec91e7cfab9af71ad88d81ab4cb80aadaf6e2d5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
